const topics = {
    "Angielski Temat 1": [
        { pl: "akcent", en: "accent" },
        { pl: "zadanie", en: "assignment" },
        { pl: "chodzić do szkoły", en: "attend school" },
        { pl: "ściągać", en: "cheat" },
        { pl: "nauczanie zdalne", en: "distance learning" },
        { pl: "wykonać projekt", en: "do a project" },
        { pl: "uzyskać pomoc", en: "get help" },
        { pl: "wyrażać się", en: "express yourself" },
        { pl: "mieć zaległości w nauce", en: "fall behind with schoolwork" },
        { pl: "zdobywać wiedzę", en: "gain knowledge" },
        { pl: "dostać dobrą ocenę", en: "get a good grade" },
        { pl: "prowadzić rozmowę", en: "have a conversation" },
        { pl: "poprawić umiejętności", en: "improve your skills" },
        { pl: "nauczyć się nowej umiejętności", en: "learn a new skill" },
        { pl: "skończyć szkołę", en: "leave school" },
        { pl: "motywować", en: "motivate" },
        { pl: "native speaker", en: "native speaker" },
        { pl: "ćwiczyć", en: "practise" },
        { pl: "świadectwo szkolne", en: "school certificate" },
        { pl: "nadzorować", en: "supervise" }
    ],
    "Niemiecki Temat 1": [
        { pl: "nazywać", en: "nennen", perf: "hat genannt" },
        { pl: "gwizdać", en: "pfeifen", perf: "hat gepfiffen" },
        { pl: "radzić", en: "raten", perf: "hat geraten" },
        { pl: "jeździć konno", en: "reiten", perf: "hat geritten" },
        { pl: "pachnieć", en: "riechen", perf: "hat gerochen" },
        { pl: "wołać", en: "rufen", perf: "hat gerufen" },
        { pl: "solić", en: "salzen", perf: "hat gesalzen" },
        { pl: "ssać", en: "saugen", perf: "hat gesogen" },
        { pl: "tworzyć", en: "schaffen", perf: "hat geschaffen" },
        { pl: "rozwodzić", en: "scheiden", perf: "hat geschieden" },
        { pl: "świecić", en: "scheinen", perf: "hat geschienen" },
        { pl: "kosić", en: "scheren", perf: "hat geschoren" },
        { pl: "przesuwać", en: "schieben", perf: "hat geschoben" },
        { pl: "strzelać", en: "schießen", perf: "hat geschossen" },
        { pl: "spać", en: "schlafen", perf: "hat geschlafen" },
        { pl: "bić", en: "schlagen", perf: "hat geschlagen" },
        { pl: "zamykać", en: "schließen", perf: "hat geschlossen" },
        { pl: "topić", en: "schmelzen", perf: "hat geschmolzen" },
        { pl: "ciąć", en: "schneiden", perf: "hat geschnitten" },
        { pl: "pisać", en: "schreiben", perf: "hat geschrieben" },
        { pl: "krzyczeć", en: "schreien", perf: "hat geschrien" },
        { pl: "milczeć", en: "schweigen", perf: "hat geschwiegen" },
        { pl: "pływać", en: "schwimmen", perf: "hat geschwommen" },
        { pl: "widzieć", en: "sehen", perf: "hat gesehen" },
        { pl: "wysyłać", en: "senden", perf: "hat gesandt" },
        { pl: "śpiewać", en: "singen", perf: "hat gesungen" }
    ]
};
